[[redirects]]
  from = "/api/gracias"
  to = "/gracias"
  status = 301
  force = false

[[redirects]]
  from = "/api/contacto"
  to = "/contacto"
  status = 301
  force = false

[[redirects]]
  from = "/api/selector-de-producto/resultado"
  to = "/selector-de-producto/resultado"
  status = 301
  force = false

[[redirects]]
  from = "/profesionales"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/soluciones/*"
  to = "/productos"
  status = 301
  force = false